# Generated by Django 3.1.7 on 2021-05-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weapon_Type',
            field=models.CharField(choices=[('AN', 'Ammo'), ('FE', 'Fin'), ('HY', 'Heavy'), ('ID', 'Improv'), ('LT', 'Light'), ('LG', 'Load'), ('ML', 'Martial'), ('RD', 'Range'), ('RH', 'Reach'), ('SL', 'Special'), ('TN', 'Thrown'), ('TD', 'TwoHand'), ('VE', 'Vers')], default='AN', max_length=2),
        ),
    ]
