# Generated by Django 3.1.7 on 2021-05-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Review', '0002_auto_20210505_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('CH', 'Cash'), ('CT', 'Credit')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='weapon_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_Total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_Review.order')),
                ('weapon_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_Review.weapon')),
            ],
        ),
    ]
