# Generated by Django 3.1.7 on 2021-05-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Review', '0005_auto_20210506_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weapon_Stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
