# Generated by Django 3.1.7 on 2021-05-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Review', '0006_weapon_weapon_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
