# Generated by Django 3.1.7 on 2021-05-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Review', '0007_remove_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon_order',
            name='line_Total',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='weapon_order',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
