# Generated by Django 3.1.7 on 2021-05-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Review', '0008_auto_20210509_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
